### ISSUE TITLE
option to suppress tqdm in extract_bs

### ISSUE THREAD

**Issue by benjaminpope** [SydneyAstrophotonicInstrumentationLab/AMICAL#121]
At line 119 of bispect.py, there is a tqdm loop for 'Extracting in the cube'.

If you want to loop over many files, you should be able to disable this progress bar.

I suggest using the `disable` keyword argument of `tqdm` : `tqdm(..., disable=True)`.

Same applies to the 'CP covariance' tqdm in `_compute_cp_cov`

**Comment by DrSoulain** [comment]
Hi @benjaminpope, thanks for your comment. In the last release v1.4, the CLI version of AMICAL can deal with many files (with a global progress bar over the files) and one (disappearing) progress bar for each individual file. The proper documentation will come soon but you can check how work the CLI with amical -h (command line).

Anyway, do you think it would be good to disable the progress bar? I do not know why but maybe you were facing some issues?

**Comment by benjaminpope** [comment]
I don't think we want to disable it in general! But if you want to write a custom loop over many files, using Amical, you probably want options both to suppress verbose behaviour and `tqdm`, so that you can optionally control logging at the outside of the loop.

**Comment by DrSoulain** [comment]
You can now add verbose = False in extract_bs() to turn the amical extraction in quiet mode (added in #128).

**Comment by DrSoulain** [comment]
Yes, verbose was already implemented, I just add the disable of the tqdm (see #128).

**Comment by benjaminpope** [comment]
Hero!

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________
