### ISSUE TITLE
Adding ERIS SAM

### ISSUE THREAD

**Issue by JHayoz** [SydneyAstrophotonicInstrumentationLab/AMICAL#143]
Dear developers of AMICAL,

I'm participating in the commissioning of the new ERIS instrument at VLT and, along with the two coronagraphs, I'm responsible for the 3 SAM masks in NIX (SAM-7, 9, and 23). How can I add support for those in AMICAL? Is there a simple workflow to add support for a new instrument?

Thanks for your help!

Jean

**Comment by DrSoulain** [comment]
Hi @JHayoz, thanks for your interest :) For now, we do not have a proper workflow to add new instruments. The main requirement for AMICAL is to have access to an accurate determination of the aperture positions (compared to the pupil in meters) and the wavelength domain of the instrument (central wavelength, bandwidth, etc.). You can have a look at [get_infos_obs.py](amical/get_infos_obs.py) to see the structure required by AMICAL.

**Comment by DrSoulain** [comment]
Hi again @JHayoz; additionally, if you have some simulated data, we can manage to test the pipeline on them. We probably need to know what are the appropriate header keywords to select the filters automatically, but this can be solved in a second step. Let me know when you have a reasonable estimate of your mask properties and associated spectral filters :)

**Comment by JHayoz** [comment]
Hi, thanks for your answers! I don't have simulated data, just data taken during commissioning. I have pupil images with the different SAM masks inserted as well as the design of the SAMs, so in principle this should provide all the data we need. I have to look into get_infos_obs.py to understand how to provide this info to AMICAL though. I'll try it this week and will probably have some more questions about AMICAL as I go.
