### ISSUE TITLE
Option to save CANDID plots

### ISSUE THREAD

**Issue by rcooper295** [SydneyAstrophotonicInstrumentationLab/AMICAL#18]
It would be very useful to be able to save the plots CANDID produces, maybe with an optional "save" parameter in amical.plot_model() and amical.candid_cr_limit(), with either a default name based on the input OIFITS file or a custom name that the user can pass as an optional argument.

**Comment by DrSoulain** [comment]
Good idea, actually I just save the figure using the graphical interface of matplotlib but I will definitely add an option to save the figure during the process, thanks @rcooper295 .

**Comment by DrSoulain** [comment]
New feature added in 72f8fc54fe328c1cda125cf47af95f5d4029c3bf.
