### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by benjaminpope** [SydneyAstrophotonicInstrumentationLab/AMICAL#22]
Hi Anthony,

Just cloned and ran `example_analysis.py`: hit this problem right away.

```

In [1]: run example_analysis.py
 | --- Start CANDID fitting --- :
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/code/AMICAL/doc/example_analysis.py in <module>
     40                     }
     41 
---> 42     fit1 = amical.candid_grid(inputdata, **param_candid, diam=20, doNotFit=[])
     43 
     44     cr_candid = amical.candid_cr_limit(

~/opt/anaconda3/lib/python3.8/site-packages/amical-1.2-py3.8.egg/amical/analysis/easy_candid.py in candid_grid(input_data, step, rmin, rmax, diam, obs, extra_error_cp, err_scale, extra_error_v2, instruments, doNotFit, ncore, verbose)
     36 
     37     cprint(' | --- Start CANDID fitting --- :', 'green')
---> 38     o = candid.Open(input_data, extra_error=extra_error_cp,
     39                     err_scale=err_scale, extra_error_v2=extra_error_v2,
     40                     instruments=instruments)

~/opt/anaconda3/lib/python3.8/site-packages/amical-1.2-py3.8.egg/amical/externals/candid/candid.py in __init__(self, filename, rmin, rmax, reducePoly, wlOffset, alpha, v2bias, instruments, largeCP, err_scale, extra_error, extra_error_v2)
   1150         if verbose:
   1151             print(' | compute aux data for companion injection')
-> 1152         self._compute_delta()
   1153         # self.estimateCorrSpecChannels()
   1154 

~/opt/anaconda3/lib/python3.8/site-packages/amical-1.2-py3.8.egg/amical/externals/candid/candid.py in _compute_delta(self)
   1606         allV2 = {'u': np.array([]), 'v': np.array([]), 'mjd': np.array([]),
   1607                  'wl': np.array([]), 'v2': np.array([])}
-> 1608         for r in filter(lambda x: x[0].split(';')[0] == 'v2', self._rawData):
   1609             allV2['u'] = np.append(allV2['u'], r[1].flatten())
   1610             allV2['v'] = np.append(allV2['v'], r[2].flatten())

AttributeError: 'Open' object has no attribute '_rawData'
```

**Comment by vandalt** [comment]
Hi,

I also ran into this issue For me the problem was that the oifits had not been generated. I had to run the extraction script, `expample_NIRISS.py`, before the analysis script.

@DrSoulain, do you think this corner case can be handled directly in the `candid.Open` initialization? Right now it seems this case is just ignored and an error is raised only when AMICAL tries to access tha `_rawData` attribute. I have a fix locally that just raises an error at initialization if the filename is not valid, I can send it upstream (it's just a 2 line `else` clause near the end of the `__init__` method).

**Comment by DrSoulain** [comment]
Thanks for that, indeed, example_analysis.py script doesn't work if you don't have the extracted oifits file at the expected location (so as Thomas said, you just need to run the extracting script first). Sure, @vandalt is you have the fix to directly handle the missing/wrong files location into candid, you can propose a PR or I can do it too.

**Comment by neutrinoceros** [comment]
I report that even running

```
cd examples
# produce the "missing file"
python example_NIRISS.py
python example_analysis.py
```
the last call seems to get stuck in a loop, spawning RuntimeErrors for ever.
My take here is that these example script are not worth maintaining and should be migrated to an actual CLI (as we already discussed offline).

**Comment by neutrinoceros** [comment]
maybe I ought to open a separate issue though, I'm not 100% sure that these are related. Disregard if not.

**Comment by vandalt** [comment]
I just updated my local repo, and ran this:
```
cd doc
python example_NIRISS.py
python example_analysis.py
```
Everything worked OK for both scripts. @neutrinoceros  You used `cd examples` instead of `cd doc` above, is this a modified version of the example scripts or you just renamed the directory ?

**Comment by neutrinoceros** [comment]
oh sorry, that's a mistake I made while reporting... indeed, I meant to type `cd doc`

**Comment by neutrinoceros** [comment]
ok let's open a different issue. Sorry about the noise.

**Comment by vandalt** [comment]
Should this issue be closed, now that an error has been added for when the file is missing ? @DrSoulain  @benjaminpope
