### ISSUE TITLE
Pymask crashes due to missing DATE-OBS in simulated data

### ISSUE THREAD

**Issue by vandalt** [SydneyAstrophotonicInstrumentationLab/AMICAL#46]
For simulated data, a few keys, including DATE-OBS, are not saved in the `infos` attribute of the extraction result ([see code here](https://github.com/SydneyAstrophotonicInstrumentationLab/AMICAL/blob/master/amical/mf_pipeline/bispect.py#L996)). Then the `save` function simply replaces DATE-OBS with an empty string. This causes Pymask to crash for simulated data, even if the simulated data had a DATE-OBS to begin with (because it is lost in the extraction step), see the error message below.

I fixed this locally by making `_add_infos_header` parse `add_keys` for simulated data too, but with a try/except and using `hdr[key]` to access info. This way to behaviour is unchanged for simulated data when keys are missing. This fixes the error for simulated data that has a DATE-OBS value.

For simulated data without a DATE-OBS originally (this is the case of the example NIRISS data), two options I see would be to use a placeholder in the `_add_infos_header` function and/or to add logic inside Pymask to handle empty DATE-OBS without crashing. The latter seems more intuitive, so that if the original observations have no DATE-OBS, the extracted oifits also has none, but I'm not familiar with fits/oifits conventions.

If you want I can send a patch, just let me know which option is best for the empty DATE-OBS case.

```python
Traceback (most recent call last):
  File "example_analysis.py", line 78, in <module>
    fit2 = amical.pymask_grid(inputdata, **param_pymask)
  File "/home/vandal/astro/AMICAL/amical/analysis/easy_pymask.py", line 52, in pymask_grid
    cpo = pymask.cpo(input_data)
  File "/home/vandal/astro/AMICAL/amical/externals/pymask/cpo.py", line 74, in __init__
    self.extract_multi_oifits(oifits)
  File "/home/vandal/astro/AMICAL/amical/externals/pymask/cpo.py", line 126, in extract_multi_oifits
    self.extract_from_oifits(f)
  File "/home/vandal/astro/AMICAL/amical/externals/pymask/cpo.py", line 81, in extract_from_oifits
    data = oifits.open(filename)
  File "/home/vandal/astro/AMICAL/amical/externals/pymask/oifits.py", line 2030, in open
    int(date[0]), int(date[1]), int(date[2])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by DrSoulain** [comment]
Thanks @vandalt. Indeed, we can handle that directly in Pymask (DATE-OBS is not supposed to be mandatory so it's weird). You can propose a patch please yes. Also, I tested Pymask using simulated NIRISS data with Ami-sim but I can imagine that the header are not computed in the same way. Actually, the pymask behaviour is not fully tested yet, we definitely want to improve this in the near future.

**Comment by vandalt** [comment]
Sounds good. Is it OK if I add a failing test too ? I would copy the test.oifits and remove the `DATE-OBS` to perform the test ?

**Comment by vandalt** [comment]
Also, @DrSoulain, in Pymask, would it be better if the date was set to some placeholder value, and if yes which value ? Otherwise, maybe `timeobs` could simply be set with the "delta" part when date is an empty string. Which option do you prefer? ([code here](https://github.com/SydneyAstrophotonicInstrumentationLab/AMICAL/blob/master/amical/externals/pymask/oifits.py#L1964))
