### ISSUE TITLE
"double display" of figures in Jupyter notebooks

### ISSUE THREAD

**Issue by neutrinoceros** [SydneyAstrophotonicInstrumentationLab/AMICAL#53]
using AMICAL's api to produce figures in a notebook sometimes results in a single figure being displayed more than one time. Most likely this is due to a combination of calling `plt.show()` internally (which should be avoided) and returning handles to figures created (which is a good thing).

I think that this will be solved when we implement an actual CLI, and reserved calling `plt.show` there, rather than _inside_ functions.

**Comment by DrSoulain** [comment]
Thanks @neutrinoceros, I will manage to remove double plt.show() for the plotting related stuff to be compliant with notebook uses. The CLI version is on its way 😉
