### ISSUE TITLE
Example scripts get stuck in a loop

### ISSUE THREAD

**Issue by neutrinoceros** [SydneyAstrophotonicInstrumentationLab/AMICAL#54]
The following script (run from the top level of the repo) fails badly on my machine (gets stuck in a loop spawning RuntimeErrors)
```shell
cd doc
python example_NIRISS.py
python example_analysis.py
```

Interestingly, @vandalt reports that the same script works on his install ! so let's see if we can figure out what's the important difference here:

OS : OSX 11.4
Python version: 3.9.4
matplotlib version : 3.4.2
Astropy version : 4.2.1
amical version : current master (19e522ea8d97504d540c7f556e4fdfb264c78c93)

I installed Python with pyenv + virtualenv, then AMICAL and its deps with `python -m pip install -e .`

**Comment by vandalt** [comment]
I just tested with the same configuration (appart from the OS) and it worked. I also installed Python with pyenv and created an environemnt with pyenv-virtualenv, then installed with `python -m pip install -e .`.

Here's my summary:

Linux-5.12.12-300.fc34.x86_64-x86_64-with-glibc2.33 (Fedora)
Python 3.9.4 (default, Jun 30 2021, 15:04:22) 
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
numpy 1.21.0
astropy 4.2.1
matplotlib 3.4.2
amical version: current master ([`19e522e`](https://github.com/SydneyAstrophotonicInstrumentationLab/AMICAL/commit/19e522ea8d97504d540c7f556e4fdfb264c78c93))

**Comment by neutrinoceros** [comment]
ok, let's play a game. If the OS is the only problem, which actually seems likely because @DrSoulain is also running OsX and reported having the same problem offline, we should be able to see it in CI. I'll open a dummy PR to try to expose this

**Comment by DrSoulain** [comment]
Fixed with #72
