### ISSUE TITLE
Enhancement: Enable more flexible background/sky subraction

### ISSUE THREAD

**Issue by vandalt** [SydneyAstrophotonicInstrumentationLab/AMICAL#80]
Currently, background subtraction is done after the image is cropped and is limited to a ring around the PSF. In most cases this is fine, but as in #79, the small size of NIRISS images gave me some problems. When the fringe pattern is ~centered, the current method works fine, but if the image is off-centered, the background is restricted to a very small right, and is very near the fringe patterns. Here are a few possible changes that could help:
1. Do sky subraction before cropping the image, allowing users to define a ring in the full image. This leaves a bigger choice of pixels to use, even if the background ring ends up being a circular arc instead of a full circle
2. Allow users to provide either a boolean mask to use for sky subtraction, or to provide functions that can be used instead of the default `sky_correction` function. (I think a boolean mask would give a lot of flexibility and require relatively simple changes to AMICAL)

In the case of relatively small images (example NIRISS 80x80 images), I think the first point above, or something similar, is necessary to make the sky subtraction useful with NIRISS data and does not really affect other instruments. The second point would be nice to have as well, although less essential.

@DrSoulain, let me know what you think, I'd be happy to send a PR for this.

**Comment by DrSoulain** [comment]
Solved by #85.
