### ISSUE TITLE
Calibrating pupil-stabilized data

### ISSUE THREAD

**Issue by tomasstolker** [SydneyAstrophotonicInstrumentationLab/AMICAL#96]
Hello AMICAL team,

Thanks a lot for providing this great pipeline!

I have a question about calibrating data that are obtained with pupil instead of field tracking.

Sorry if I may have misunderstood how this works because I am new with NRM data analysis. As far as I could tell, AMICAL only supports the use of a constant value for the position angle (i.e. the `pa` parameter), correct? With pupil-stabilized observations, the value of `pa` changes during the observation, which then nicely increases the uv coverage. In `tools.compute_pa`, the mean position angle is returned, while I would have expected that the actual position angle of each frame is required?

I managed to reduce a SPHERE dataset by simply creating a for loop over the exposure/angles, but storing the data with `save` (by passing a list to `observables`) and then running the analysis tools does not seem to work. I think because `observables` may support a list of observables from different wavelengths but not from different position angles?

Is there something that I have misunderstood or does AMICAL simply not (yet?) support the calibration of pupil-tracking data?

Thanks a lot and keep up the great work 😊

**Comment by DrSoulain** [comment]
Hi @tomasstolker, thanks for your feedback. Indeed, the pa is averaged and used to compute the correct orientation. Usually, the PA do not change a lot within a single dataset so the u-v coverage do suffer that much (no blur). For the testing dataset of SPHERE, we used indeed the pupil-stabilized mode, and notice that the change of PA is ok. Normally, you should see a similar plot of the joined one to check if the pa do not vary too much for your personal dataset. If you really want to take into account a larger PA difference, you should split your dataset accordingly. But the idea keep a large enough number of frames to get a good statistics and the observable uncertainty.

<p align="center">
<img src="https://user-images.githubusercontent.com/11616707/151351205-71194cc4-d747-44a2-80b1-4f3f8088d0f2.png" width="50%">
</p>

**Comment by tomasstolker** [comment]
Is the plot showing only the pupil offset? The parallactic angle typically changes by many degrees so the total variation of the position angle would be larger?

I think that I have managed to get it to work by creating a separate OIFITS file for each position instead of trying to combine all data in a file. If I then pass the list of files to `candid_grid` and `candid_cr_limit` then it seems to work 😊.

One small issue that I noticed is that `save=True` does not work in these two analysis functions when the input data is a list of files because of `os.path.basename(input_data)`.

Thanks for you help!

**Comment by neutrinoceros** [comment]
> One small issue that I noticed is that save=True does not work in these two analysis functions when the input data is a list of files because of os.path.basename(input_data).

Thank for reporting this. It is fixed in #101 and will be part of the upcoming release.

**Comment by tomasstolker** [comment]
Thanks for your replies!

If the plot shows the position angle of the telescope pupil then the variation is indeed expected to be small over time. There is however also the parallactic rotation for pupil-stabilized observations (e.g. SPHERE/SAM), which could vary by a lot. The parallactic angles seem to be calculated with the `sphere_parang` function in `compute_pa`, but then taking the mean (i.e. `np.mean(l_pa)` in `compute_pa`) would be inaccurate I think, unless the field rotation happens to be small at that moment. Sorry if I might still be misunderstanding the code... I could circumvent this by running the AMICAL functions on the individual exposures within a `for` loop. That works fine but some clarification in the docstring of the `pa` parameter could perhaps help.

One other thing that I noticed is that the u-v coordinates that are returned by `extract_bs` have not been corrected by the position angle, correct? Perhaps this was done on purpose but since `pa` is an input parameter of that function I would have expected that it is folded in the calculation of the u-v coordinates.

Thanks again for all your work on this excellent pipeline!

**Comment by DrSoulain** [comment]
That's correct. 

For us, we considered that half degree was not too big and we decided to compute the average but it's maybe not correct for all targets. In the test case of SPHERE, we used all the exposure to get a good enough SNR and compute the uncertainties with appropriate statistics but we should maybe consider other science cases. 

Actually, in sphere_parang(), we raise a warning if the rotation is bigger than a degree. If you have suggestions to take into account a proper rotation for each individual frame do not hesitate. But in any case, we used all the frames to compute the observables, so we need to average the corresponding PA at the end.

Indeed, the pa is part of bispectrum extraction but it is applied only at the end (to plot the data or save the oifits file). We keep the u-v coverage untouched before to ensure that we sample the Fourier space correctly (without ambiguity on the rotation).

**Comment by tomasstolker** [comment]
Thanks, that is good to know! Allowing for a larger change in position/parallactic angle would probably require quite some changes in the code so using a `for` loop with the calibration (by the user) might be easiest solution. Typically, the parallactic rotation will be large though (i.e. many degrees), since the scheduling of these observations is usually optimized for that.

I actually just noticed that there is not a `pa` parameter in `extract_bs`, but I had added that parameter (and the poor docstring...) myself 🙈. Maybe it could be useful to add actually. If the argument is set to `None` then it will run the `pa = compute_pa()` line, otherwise it can take a float. The latter is what I have been using because I am calculating the angles separately, so that's why I didn't ran into the warning of `sphere_parang`.

**Comment by DrSoulain** [comment]
You can in any way use your own pa to save the oifits file or plot your observables. We do not really care about the pa at the extraction step. We include the SPHERE consortium function to compute the pa within amical (and are implementing the same for other instruments) but in the end, it's a user choice.
